version: "2.2"
services:
  timemachine:
    image: evenstay/netatalk-tm:latest
    volumes:
      - ${TIMEMACHINE_VOLUME:-/mnt/timemachine}:/timemachine
      - tm-cnid-data:/var/netatalk
    restart: unless-stopped
    mem_limit: 512m
    network_mode: host
    hostname: timemachine
    ports:
      - "548:548"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
volumes:
  tm-cnid-data:
